# Generated by Django 5.2.8 on 2025-11-23 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Örn: 1. Hafta - Detoks Listesi', max_length=100, verbose_name='Program Adı')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Program mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='diet_programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Gün')),
                ('breakfast', models.TextField(blank=True, verbose_name='Kahvaltı')),
                ('lunch', models.TextField(blank=True, verbose_name='Öğle Yemeği')),
                ('dinner', models.TextField(blank=True, verbose_name='Akşam Yemeği')),
                ('snack_1', models.TextField(blank=True, verbose_name='Ara Öğün 1 (Kuşluk)')),
                ('snack_2', models.TextField(blank=True, verbose_name='Ara Öğün 2 (İkindi)')),
                ('snack_3', models.TextField(blank=True, verbose_name='Ara Öğün 3 (Gece)')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='nutrition.dietprogram')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('program', 'day_of_week')},
            },
        ),
    ]
