# Generated by Django 5.2.8 on 2025-11-22 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Görev Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('points', models.IntegerField(default=10, verbose_name='Puan Değeri')),
                ('task_type', models.CharField(choices=[('MANUAL', 'Manuel'), ('PHOTO', 'Fotoğraf'), ('WATER', 'Su')], default='MANUAL', max_length=20, verbose_name='Görev Tipi')),
                ('related_meal_type', models.CharField(blank=True, choices=[('kahvalti', 'Kahvaltı'), ('ogle', 'Öğle Yemeği'), ('aksam', 'Akşam Yemeği'), ('araogun', 'Ara Öğün')], max_length=50, null=True, verbose_name='İlişkili Öğün')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_for_everyone', models.BooleanField(default=False, verbose_name='Tüm Danışanlara Ata')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, help_text='Boş bırakılırsa süresiz olur.', null=True, verbose_name='Bitiş Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(auto_now_add=True, verbose_name='Tamamlanma Tarihi')),
            ],
        ),
    ]
