# Generated by Django 5.2.8 on 2025-11-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_initial'),
        ('gamification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletion',
            name='meal_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diary.mealphoto'),
        ),
    ]
