# Generated by Django 5.2.8 on 2025-11-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_date_of_birth_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Erkek'), ('FEMALE', 'Kadın'), ('OTHER', 'Belirtmek İstemiyorum')], max_length=10, null=True, verbose_name='Cinsiyet'),
        ),
    ]
