# Generated by Django 5.2.8 on 2025-11-22 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('current_amount', models.PositiveIntegerField(default=0)),
                ('target_amount', models.PositiveIntegerField(default=2500)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('gender', models.CharField(choices=[('M', 'Erkek'), ('F', 'Kadın')], default='F', max_length=1, verbose_name='Cinsiyet')),
                ('height', models.PositiveIntegerField(blank=True, help_text='Örn: 175', null=True, verbose_name='Boy (cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, help_text='Örn: 70.5', max_digits=5, null=True, verbose_name='Kilo (kg)')),
                ('chronic_diseases', models.TextField(blank=True, help_text='Örn: Diyabet Tip 2, Haşimato, Hipertansiyon', verbose_name='Kronik Rahatsızlıklar')),
                ('allergies', models.TextField(blank=True, help_text='Örn: Gluten, Laktoz, Fıstık', verbose_name='Alerjiler & İntoleranslar')),
                ('medications', models.TextField(blank=True, help_text='Düzenli kullanılan ilaçlar.', verbose_name='Kullanılan İlaçlar')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Hareketsiz (Masa başı)'), ('light', 'Az Hareketli (Haftada 1-3 gün spor)'), ('moderate', 'Orta Hareketli (Haftada 3-5 gün spor)'), ('active', 'Çok Hareketli (Haftada 6-7 gün spor)'), ('athlete', 'Profesyonel Sporcu')], default='sedentary', max_length=20, verbose_name='Aktivite Seviyesi')),
                ('goal_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Hedef Kilo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
