# Generated by Django 5.2.8 on 2025-11-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='daily_activity',
            field=models.CharField(choices=[('sedentary', 'Hareketsiz (Masa başı)'), ('light', 'Az Hareketli (Haftada 1-3 gün spor)'), ('moderate', 'Orta Hareketli (Haftada 3-5 gün spor)'), ('active', 'Çok Hareketli (Haftada 6-7 gün spor)'), ('athlete', 'Profesyonel Sporcu')], default='sedentary', max_length=50, verbose_name='Günlük Hareket'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='diet_preference',
            field=models.CharField(choices=[('standard', 'Her şeyi yerim'), ('vegan', 'Vegan'), ('vegetarian', 'Vejetaryen'), ('ketogenic', 'Ketojenik'), ('gluten_free', 'Glutensiz')], default='standard', max_length=50, verbose_name='Beslenme Tipi'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='disliked_foods',
            field=models.TextField(blank=True, help_text='Örn: Brokoli, Mantar...', verbose_name='Sevmediği Besinler'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='is_onboarding_complete',
            field=models.BooleanField(default=False, verbose_name='Sihirbaz Tamamlandı mı?'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='motivation_level',
            field=models.IntegerField(default=5, verbose_name='Motivasyon Seviyesi (1-10)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='target_date',
            field=models.DateField(blank=True, help_text='Bu kiloya ne zaman ulaşmak istiyorsun?', null=True, verbose_name='Hedef Tarih'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='water_habit',
            field=models.CharField(choices=[('bad', 'Çok az içiyorum (<1L)'), ('medium', 'Ortalama (1.5L - 2L)'), ('good', 'Çok iyi (>2.5L)')], default='medium', max_length=50, verbose_name='Su İçme Alışkanlığı'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='Örn: Gluten, Laktoz', verbose_name='Alerjiler & İntoleranslar'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='chronic_diseases',
            field=models.TextField(blank=True, help_text='Örn: Diyabet Tip 2, Haşimato', verbose_name='Kronik Rahatsızlıklar'),
        ),
    ]
