# Generated by Django 5.2.7 on 2025-11-24 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietitianAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Gün')),
                ('start_time', models.TimeField(verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
                ('slot_length_minutes', models.PositiveIntegerField(default=60, verbose_name='Randevu Süresi (Dk)')),
                ('dietitian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL, verbose_name='Diyetisyen')),
            ],
            options={
                'verbose_name': 'Çalışma Saati',
                'verbose_name_plural': 'Çalışma Saatleri',
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('dietitian', 'weekday', 'start_time')},
            },
        ),
    ]
