# Generated by Django 5.2.8 on 2025-11-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='meal_photos/%Y/%m/%d/', verbose_name='Fotoğraf')),
                ('meal_type', models.CharField(choices=[('kahvalti', 'Kahvaltı'), ('ogle', 'Öğle Yemeği'), ('aksam', 'Akşam Yemeği'), ('araogun', 'Ara Öğün')], max_length=20, verbose_name='Öğün Tipi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
