# Generated by Django 5.2.8 on 2025-11-23 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Paket Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('currency', models.CharField(default='₺', max_length=3, verbose_name='Para Birimi')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Süre (Gün)')),
                ('description', models.TextField(blank=True, verbose_name='Kısa Açıklama')),
                ('is_popular', models.BooleanField(default=False, verbose_name='En Popüler')),
                ('icon_class', models.CharField(default='bi-star', help_text='Bootstrap Icon', max_length=50, verbose_name='İkon Class')),
                ('color_theme', models.CharField(default='primary', help_text='primary, success, warning vb.', max_length=20, verbose_name='Renk Teması')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Özellik')),
                ('is_included', models.BooleanField(default=True, verbose_name='Dahil mi?')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='plans.dietplan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin Notu')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.dietplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
