# Generated by Django 3.2.9 on 2025-11-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tarif Başlığı')),
                ('image', models.ImageField(upload_to='recipes/', verbose_name='Kapak Fotoğrafı')),
                ('ingredients', models.TextField(help_text='Her malzemeyi yeni bir satıra yazın.', verbose_name='Malzemeler')),
                ('instructions', models.TextField(help_text='Her adımı yeni bir satıra yazın.', verbose_name='Hazırlanışı')),
                ('calories', models.PositiveIntegerField(verbose_name='Kalori (kcal)')),
                ('prep_time', models.PositiveIntegerField(verbose_name='Hazırlama Süresi (dk)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifler',
                'ordering': ['-created_at'],
            },
        ),
    ]
